/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        noto: ["Noto Sans Thai", "sans-serif"],
        kanit: ["Kanit", "sans-serif"],
        sans: ["Sarabun", "sans-serif"],
      },
      zIndex: {
        "-1": "-1",
        auto: "auto",
        0: "0",
        base: "0",
        docked: "10",
        dropdown: "1000",
        sticky: "1100",
        banner: "1200",
        overlay: "1300",
        modal: "1400",
        popover: "1500",
        skipLink: "1600",
        toast: "1700",
        tooltip: "1800",
      },
      screens: {
        "mobile-sm": "320px",
        mobile: "375px",
        "tablet-sm": "600px",
        tablet: "768px",
        "tablet-lg": "900px",
        laptop: "1024px",
        "laptop-lg": "1280px",
        desktop: "1440px",
        "desktop-lg": "1600px",
        "4k": "2560px",
      },
      colors: {
        primary: "#4C51BF",
        "primary-light": "#B2B7FF",
        "primary-dark": "#2A3B94",
        "primary-content": "#FFFFFF",

        secondary: "#7C3AED",
        "secondary-light": "#D6B2FF",
        "secondary-dark": "#5522A6",
        "secondary-content": "#FFFFFF",

        neutral: "#6C757D",
        "neutral-light": "#D1D5DB",
        "neutral-dark": "#343A40",
        "neutral-content": "#FFFFFF",

        bases: "#FFFFFF",
        "bases-light": "#F0F0ED",
        "bases-dark": "#B0B0AD",
        "bases-content": "#000000",

        accent: "#FA8246",
        "accent-light": "#FFCBA8",
        "accent-dark": "#B55420",
        "accent-content": "#FFFFFF",

        info: "#3DA9FC",
        "info-light": "#A6D8FF",
        "info-dark": "#247BBF",
        "info-content": "#FFFFFF",

        warning: "#FFB020",
        "warning-light": "#FFD080",
        "warning-dark": "#C77B16",
        "warning-content": "#000000",

        error: "#E53E3E",
        "error-light": "#FCA5A5",
        "error-dark": "#B83232",
        "error-content": "#FFFFFF",

        success: "#50A970",
        "success-light": "#A8DAB5",
        "success-dark": "#2E734A",
        "success-content": "#FFFFFF",

        "risk-level-0": "#e0f2f1",
        "risk-level-0-light": "#ffffff",
        "risk-level-0-dark": "#c2d0cd",
        "risk-level-0-content": "#004d40",
        "risk-level-1": "#b9fbc0",
        "risk-level-1-light": "#d1f8d2",
        "risk-level-1-dark": "#8acb8d",
        "risk-level-1-content": "#004d40",
        "risk-level-2": "#a2d9b1",
        "risk-level-2-light": "#c5e4c3",
        "risk-level-2-dark": "#7aab85",
        "risk-level-2-content": "#004d40",
        "risk-level-3": "#ffcc00",
        "risk-level-3-light": "#ffe066",
        "risk-level-3-dark": "#e0a700",
        "risk-level-3-content": "#000000",
        "risk-level-4": "#ff9900",
        "risk-level-4-light": "#ffb84d",
        "risk-level-4-dark": "#e68a00",
        "risk-level-4-content": "#000000",
        "risk-level-5": "#ff3300",
        "risk-level-5-light": "#ff6f6f",
        "risk-level-5-dark": "#c60000",
        "risk-level-5-content": "#ffffff",
      },
      extend: {},
    },
    plugins: [],
  },
};
